import type { Metadata } from 'next';
import '@/app/style/globals.scss';
import '@/app/style/variables.scss';
import styles from './layout.module.scss';
import Footer from '@/components/footer/footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body>
                <main className={styles.main}>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
